--drop table user_info;
create table user_info(
    id int not null,
    name varchar(20) not null,
    password varchar(15) not null,
    email varchar(20),
    role varchar(10) not null default 'guest',
    primary key (id)
);
--id bigint generated by default as identity