server:
    port: 8080
spring:
    # H2 DATABASE CONFIG
    # h2 web consloe 是一个数据库GUI管理应用，程序运行时，会自动启动h2 web consloe
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                # 配置后 h2 web console 就可以在远程访问，否则只能在本机访问
                web-allow-others: true
    datasource:
        # 数据库连接池
        type: com.zaxxer.hikari.HikariDataSource
        schema: classpath:/db/schema-h2.sql
        data: classpath:/db/data-h2.sql
        #数据库url,db名称随便起（这里为projectdb），项目启动后会在硬盘上自动生成db文件
        url: jdbc:h2:~/test
        #用户名
        username: sa
        #密码,项目启动成功后可以通过web console连接数据库
        password: sa
        #驱动
        driverClassName: org.h2.Driver
        platform: h2
        continue-on-error: true

#配置web console的路径，若不配置则默认就是localhost:8080/contextpath/h2-console
#如果不配置，虽然本地可以通过这个路径访问，但项目打war包发到tomcat下面，通过这个路径是访问不到的